CC=gcc

CFLAGS=-Wall

all: rmdup lsdir mkhlink

rmdup: rmdup.c
	$(CC) $(CFLAGS) rmdup.c -o bin/rmdup

lsdir: lsdir.c
	$(CC) $(CFLAGS) lsdir.c -o bin/lsdir

mkhlink: mkhlink.c
	$(CC) $(CFLAGS) mkhlink.c -o bin/mkhlink

